
### Get all posts
GET http://localhost:3003/api/blogs/

### Post new blog post
POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
    "title": "Gangstas R 4 Eva",
    "author": "Tupac Nokur",
    "url": "https://www.tupacsthots.com",
    "likes": 1170
  }